
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kuma_task_app_development

test:
  <<: *default
  database: kuma_task_app_test

production:
  <<: *default
  database: kuma_task_app_production
  username: kuma_task_app
  password: <%= ENV['KUMA_TASK_APP_DATABASE_PASSWORD'] %>
